[package]
name = "miratope"
version = "0.1.0"
authors = ["Violeta Hern√°ndez <vi.hdz.p@gmail.com>", "Grayson Burton <ocornoc@protonmail.com>"]
edition = "2018"

[dependencies]
approx = "0.4"
bevy_egui = "0.3"
dyn-clone = "1.0"
lyon = "0.17"
factorial = "0.2"
gcd = "2.0"
itertools = "0.10"
nalgebra = {version = "0.26", features = ["serde-serialize", "rand"]}
float-ord = "0.3"
petgraph = "0.5"
rand = "0.8"
regex = "1.4"
rfd = "0.3"
ron = "0.6"
scapegoat = "1.0"
serde = {version = "1.0", features = ["derive"]}
xml-rs = "0.8"
zip = "0.5"

[dependencies.bevy]
version = "0.4"
default-features = false
features = ["bevy_gltf", "bevy_winit", "bevy_wgpu", "render", "bevy_dynamic_plugin", "hdr", "x11"]

[profile.release]
lto = "thin"
incremental = true